<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use DB;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ref_province')->insert(['psgcCode'=>'012800000','provDesc'=>'ILOCOS NORTE','regionID'=>1,'regCode'=>'01','provCode'=>'0128', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'012900000','provDesc'=>'ILOCOS SUR','regionID'=>1,'regCode'=>'01','provCode'=>'0129', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'013300000','provDesc'=>'LA UNION','regionID'=>1,'regCode'=>'01','provCode'=>'0133', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'015500000','provDesc'=>'PANGASINAN','regionID'=>1,'regCode'=>'01','provCode'=>'0155', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'020900000','provDesc'=>'BATANES','regionID'=>2,'regCode'=>'02','provCode'=>'0209', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'021500000','provDesc'=>'CAGAYAN','regionID'=>2,'regCode'=>'02','provCode'=>'0215', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'023100000','provDesc'=>'ISABELA','regionID'=>2,'regCode'=>'02','provCode'=>'0231', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'025000000','provDesc'=>'NUEVA VIZCAYA','regionID'=>2,'regCode'=>'02','provCode'=>'0250', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'025700000','provDesc'=>'QUIRINO','regionID'=>2,'regCode'=>'02','provCode'=>'0257', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'030800000','provDesc'=>'BATAAN','regionID'=>3,'regCode'=>'03','provCode'=>'0308', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'031400000','provDesc'=>'BULACAN','regionID'=>3,'regCode'=>'03','provCode'=>'0314', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'034900000','provDesc'=>'NUEVA ECIJA','regionID'=>3,'regCode'=>'03','provCode'=>'0349', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'035400000','provDesc'=>'PAMPANGA','regionID'=>3,'regCode'=>'03','provCode'=>'0354', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'036900000','provDesc'=>'TARLAC','regionID'=>3,'regCode'=>'03','provCode'=>'0369', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'037100000','provDesc'=>'ZAMBALES','regionID'=>3,'regCode'=>'03','provCode'=>'0371', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'037700000','provDesc'=>'AURORA','regionID'=>3,'regCode'=>'03','provCode'=>'0377', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'041000000','provDesc'=>'BATANGAS','regionID'=>4,'regCode'=>'04','provCode'=>'0410', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'042100000','provDesc'=>'CAVITE','regionID'=>4,'regCode'=>'04','provCode'=>'0421', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'043400000','provDesc'=>'LAGUNA','regionID'=>4,'regCode'=>'04','provCode'=>'0434', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'045600000','provDesc'=>'QUEZON','regionID'=>4,'regCode'=>'04','provCode'=>'0456', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'045800000','provDesc'=>'RIZAL','regionID'=>4,'regCode'=>'04','provCode'=>'0458', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'174000000','provDesc'=>'MARINDUQUE','regionID'=>5,'regCode'=>'17','provCode'=>'1740', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'175100000','provDesc'=>'OCCIDENTAL MINDORO','regionID'=>5,'regCode'=>'17','provCode'=>'1751', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'175200000','provDesc'=>'ORIENTAL MINDORO','regionID'=>5,'regCode'=>'17','provCode'=>'1752', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'175300000','provDesc'=>'PALAWAN','regionID'=>5,'regCode'=>'17','provCode'=>'1753', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'175900000','provDesc'=>'ROMBLON','regionID'=>5,'regCode'=>'17','provCode'=>'1759', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'050500000','provDesc'=>'ALBAY','regionID'=>6,'regCode'=>'05','provCode'=>'0505', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'051600000','provDesc'=>'CAMARINES NORTE','regionID'=>6,'regCode'=>'05','provCode'=>'0516', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'051700000','provDesc'=>'CAMARINES SUR','regionID'=>6,'regCode'=>'05','provCode'=>'0517', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'052000000','provDesc'=>'CATANDUANES','regionID'=>6,'regCode'=>'05','provCode'=>'0520', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'054100000','provDesc'=>'MASBATE','regionID'=>6,'regCode'=>'05','provCode'=>'0541', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'056200000','provDesc'=>'SORSOGON','regionID'=>6,'regCode'=>'05','provCode'=>'0562', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'060400000','provDesc'=>'AKLAN','regionID'=>7,'regCode'=>'06','provCode'=>'0604', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'060600000','provDesc'=>'ANTIQUE','regionID'=>7,'regCode'=>'06','provCode'=>'0606', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'061900000','provDesc'=>'CAPIZ','regionID'=>7,'regCode'=>'06','provCode'=>'0619', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'063000000','provDesc'=>'ILOILO','regionID'=>7,'regCode'=>'06','provCode'=>'0630', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'064500000','provDesc'=>'NEGROS OCCIDENTAL','regionID'=>7,'regCode'=>'06','provCode'=>'0645', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'067900000','provDesc'=>'GUIMARAS','regionID'=>7,'regCode'=>'06','provCode'=>'0679', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'071200000','provDesc'=>'BOHOL','regionID'=>8,'regCode'=>'07','provCode'=>'0712', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'072200000','provDesc'=>'CEBU','regionID'=>8,'regCode'=>'07','provCode'=>'0722', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'074600000','provDesc'=>'NEGROS ORIENTAL','regionID'=>8,'regCode'=>'07','provCode'=>'0746', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'076100000','provDesc'=>'SIQUIJOR','regionID'=>8,'regCode'=>'07','provCode'=>'0761', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'082600000','provDesc'=>'EASTERN SAMAR','regionID'=>9,'regCode'=>'08','provCode'=>'0826', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'083700000','provDesc'=>'LEYTE','regionID'=>9,'regCode'=>'08','provCode'=>'0837', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'084800000','provDesc'=>'NORTHERN SAMAR','regionID'=>9,'regCode'=>'08','provCode'=>'0848', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'086000000','provDesc'=>'SAMAR (WESTERN SAMAR)','regionID'=>9,'regCode'=>'08','provCode'=>'0860', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'086400000','provDesc'=>'SOUTHERN LEYTE','regionID'=>9,'regCode'=>'08','provCode'=>'0864', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'087800000','provDesc'=>'BILIRAN','regionID'=>9,'regCode'=>'08','provCode'=>'0878', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'097200000','provDesc'=>'ZAMBOANGA DEL NORTE','regionID'=>10,'regCode'=>'09','provCode'=>'0972', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'097300000','provDesc'=>'ZAMBOANGA DEL SUR','regionID'=>10,'regCode'=>'09','provCode'=>'0973', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'098300000','provDesc'=>'ZAMBOANGA SIBUGAY','regionID'=>10,'regCode'=>'09','provCode'=>'0983', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'099700000','provDesc'=>'CITY OF ISABELA','regionID'=>10,'regCode'=>'09','provCode'=>'0997', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'101300000','provDesc'=>'BUKIDNON','regionID'=>11,'regCode'=>'10','provCode'=>'1013', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'101800000','provDesc'=>'CAMIGUIN','regionID'=>11,'regCode'=>'10','provCode'=>'1018', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'103500000','provDesc'=>'LANAO DEL NORTE','regionID'=>11,'regCode'=>'10','provCode'=>'1035', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'104200000','provDesc'=>'MISAMIS OCCIDENTAL','regionID'=>11,'regCode'=>'10','provCode'=>'1042', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'104300000','provDesc'=>'MISAMIS ORIENTAL','regionID'=>11,'regCode'=>'10','provCode'=>'1043', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'112300000','provDesc'=>'DAVAO DEL NORTE','regionID'=>12,'regCode'=>'11','provCode'=>'1123', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'112400000','provDesc'=>'DAVAO DEL SUR','regionID'=>12,'regCode'=>'11','provCode'=>'1124', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'112500000','provDesc'=>'DAVAO ORIENTAL','regionID'=>12,'regCode'=>'11','provCode'=>'1125', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'118200000','provDesc'=>'COMPOSTELA VALLEY','regionID'=>12,'regCode'=>'11','provCode'=>'1182', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'118600000','provDesc'=>'DAVAO OCCIDENTAL','regionID'=>12,'regCode'=>'11','provCode'=>'1186', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'124700000','provDesc'=>'COTABATO (NORTH COTABATO)','regionID'=>13,'regCode'=>'12','provCode'=>'1247', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'126300000','provDesc'=>'SOUTH COTABATO','regionID'=>13,'regCode'=>'12','provCode'=>'1263', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'126500000','provDesc'=>'SULTAN KUDARAT','regionID'=>13,'regCode'=>'12','provCode'=>'1265', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'128000000','provDesc'=>'SARANGANI','regionID'=>13,'regCode'=>'12','provCode'=>'1280', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'129800000','provDesc'=>'COTABATO CITY','regionID'=>13,'regCode'=>'12','provCode'=>'1298', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'133900000','provDesc'=>'NCR, CITY OF MANILA, FIRST DISTRICT','regionID'=>14,'regCode'=>'13','provCode'=>'1339', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'133900000','provDesc'=>'CITY OF MANILA','regionID'=>14,'regCode'=>'13','provCode'=>'1339', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'137400000','provDesc'=>'NCR, SECOND DISTRICT','regionID'=>14,'regCode'=>'13','provCode'=>'1374', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'137500000','provDesc'=>'NCR, THIRD DISTRICT','regionID'=>14,'regCode'=>'13','provCode'=>'1375', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'137600000','provDesc'=>'NCR, FOURTH DISTRICT','regionID'=>14,'regCode'=>'13','provCode'=>'1376', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'140100000','provDesc'=>'ABRA','regionID'=>15,'regCode'=>'14','provCode'=>'1401', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'141100000','provDesc'=>'BENGUET','regionID'=>15,'regCode'=>'14','provCode'=>'1411', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'142700000','provDesc'=>'IFUGAO','regionID'=>15,'regCode'=>'14','provCode'=>'1427', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'143200000','provDesc'=>'KALINGA','regionID'=>15,'regCode'=>'14','provCode'=>'1432', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'144400000','provDesc'=>'MOUNTAIN PROVINCE','regionID'=>15,'regCode'=>'14','provCode'=>'1444', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'148100000','provDesc'=>'APAYAO','regionID'=>15,'regCode'=>'14','provCode'=>'1481', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'150700000','provDesc'=>'BASILAN','regionID'=>16,'regCode'=>'15','provCode'=>'1507', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'153600000','provDesc'=>'LANAO DEL SUR','regionID'=>16,'regCode'=>'15','provCode'=>'1536', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'153800000','provDesc'=>'MAGUINDANAO','regionID'=>16,'regCode'=>'15','provCode'=>'1538', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'156600000','provDesc'=>'SULU','regionID'=>16,'regCode'=>'15','provCode'=>'1566', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'157000000','provDesc'=>'TAWI-TAWI','regionID'=>16,'regCode'=>'15','provCode'=>'1570', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'160200000','provDesc'=>'AGUSAN DEL NORTE','regionID'=>17,'regCode'=>'16','provCode'=>'1602', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'160300000','provDesc'=>'AGUSAN DEL SUR','regionID'=>17,'regCode'=>'16','provCode'=>'1603', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'166700000','provDesc'=>'SURIGAO DEL NORTE','regionID'=>17,'regCode'=>'16','provCode'=>'1667', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'166800000','provDesc'=>'SURIGAO DEL SUR','regionID'=>17,'regCode'=>'16','provCode'=>'1668', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
        DB::table('ref_province')->insert(['psgcCode'=>'168500000','provDesc'=>'DINAGAT ISLANDS','regionID'=>17,'regCode'=>'16','provCode'=>'1685', 'isSystemDefault' => 1, 'created_at' => Carbon::now('Asia/Manila'),'updated_at' => Carbon::now('Asia/Manila'),]);
    }
}
